"""Build a subset candidate CSV containing only the .obj files generated by
pipeline/convert.py's LWOB parser for source LWOs that previously failed to
import in Blender.

Logic:
  1. Walk renders/ for info.json with error == "import_failed".
  2. For each, take info["source"] (path to the original .lwo/.lw/.lwob).
  3. Check if "<source>.obj" exists on disk (LWOB parser would have written
     one if the source was a valid LWOB file).
  4. Look that .obj path up in output/candidate_models.csv to grab its
     sha256 row, and emit it to the subset CSV.

Output: output/candidate_models_import_failed_subset.csv
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RENDERS_DIR = ROOT / "renders"
CANDIDATES_CSV = ROOT / "output" / "candidate_models.csv"
SUBSET_CSV = ROOT / "output" / "candidate_models_import_failed_subset.csv"


def collect_import_failed_sources() -> list[Path]:
    sources: list[Path] = []
    for d in RENDERS_DIR.iterdir():
        if not d.is_dir():
            continue
        info_p = d / "info.json"
        if not info_p.exists():
            continue
        try:
            info = json.loads(info_p.read_text(encoding="utf-8"))
        except (ValueError, OSError):
            continue
        if info.get("error") != "import_failed":
            continue
        src = info.get("source")
        if not src:
            continue
        sources.append(Path(src))
    return sources


def candidate_obj_paths(sources: list[Path]) -> set[str]:
    """For each import_failed source, the LWOB parser would have written
    "<source>.obj" alongside it. Return the set of those .obj paths that
    actually exist on disk, normalized to lowercase strings."""
    out: set[str] = set()
    for src in sources:
        obj = src.with_name(src.name + ".obj")
        if obj.exists():
            out.add(str(obj).lower())
    return out


def main() -> None:
    sources = collect_import_failed_sources()
    print(f"import_failed sources: {len(sources)}")
    obj_paths = candidate_obj_paths(sources)
    print(f"corresponding .obj files on disk: {len(obj_paths)}")

    written = 0
    skipped_already_rendered = 0
    with CANDIDATES_CSV.open(encoding="utf-8") as fh_in, \
         SUBSET_CSV.open("w", encoding="utf-8", newline="") as fh_out:
        reader = csv.DictReader(fh_in)
        assert reader.fieldnames is not None
        writer = csv.DictWriter(fh_out, fieldnames=reader.fieldnames)
        writer.writeheader()
        for row in reader:
            p = row.get("path", "").lower()
            if p not in obj_paths:
                continue
            sha = row.get("sha256", "")
            if sha:
                # Skip ones already rendered (sentinel exists).
                sentinel = RENDERS_DIR / sha[:16] / ".render_attempted"
                if sentinel.exists():
                    skipped_already_rendered += 1
                    continue
            writer.writerow(row)
            written += 1

    print(f"wrote {written} rows to {SUBSET_CSV}")
    print(f"skipped (already rendered): {skipped_already_rendered}")


if __name__ == "__main__":
    main()
